create extension if not exists citext with schema extensions;
create extension if not exists pgcrypto with schema extensions;

create type public.connection_status as enum ('pending', 'accepted', 'rejected');
create type public.collaboration_status as enum ('open', 'closed');

create table public.campuses (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug = lower(slug)),
  name text not null unique,
  city text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.campuses (id, slug, name, city) values
  ('00000000-0000-4000-8000-000000000001', 'bangalore', 'NST Bangalore', 'Bangalore'),
  ('00000000-0000-4000-8000-000000000002', 'pune', 'NST Pune', 'Pune'),
  ('00000000-0000-4000-8000-000000000003', 'delhi-ncr', 'NST Delhi NCR', 'Delhi NCR'),
  ('00000000-0000-4000-8000-000000000004', 'hyderabad', 'NST Hyderabad', 'Hyderabad')
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  city = excluded.city,
  is_active = true;

-- Keep this table empty until the correct NST student email domain is known.
-- Add a domain with: insert into public.allowed_email_domains (domain) values ('student.example.edu');
create table public.allowed_email_domains (
  domain extensions.citext primary key,
  campus_id uuid references public.campuses(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username extensions.citext unique,
  full_name text,
  avatar_url text,
  campus_id uuid references public.campuses(id) on delete restrict,
  graduation_year smallint check (graduation_year between 2024 and 2040),
  program text,
  bio text check (char_length(bio) <= 500),
  goals text check (char_length(goals) <= 500),
  github_url text,
  linkedin_url text,
  portfolio_url text,
  is_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint username_format check (
    username is null or username::text ~ '^[a-z0-9][a-z0-9_-]{2,29}$'
  )
);

create table public.skills (
  id bigint generated by default as identity primary key,
  name extensions.citext not null unique,
  created_at timestamptz not null default now()
);

create table public.interests (
  id bigint generated by default as identity primary key,
  name extensions.citext not null unique,
  created_at timestamptz not null default now()
);

create table public.profile_skills (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  skill_id bigint not null references public.skills(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (profile_id, skill_id)
);

create table public.profile_interests (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  interest_id bigint not null references public.interests(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (profile_id, interest_id)
);

create table public.connection_requests (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  status public.connection_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  responded_at timestamptz,
  constraint connection_not_self check (requester_id <> recipient_id)
);

create unique index connection_pair_unique
  on public.connection_requests (
    least(requester_id, recipient_id),
    greatest(requester_id, recipient_id)
  );

create table public.collaboration_posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  campus_id uuid references public.campuses(id) on delete set null,
  title text not null check (char_length(title) between 5 and 100),
  description text not null check (char_length(description) between 10 and 1200),
  tags text[] not null default '{}',
  status public.collaboration_status not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index profiles_campus_idx on public.profiles(campus_id) where is_verified;
create index profiles_name_idx on public.profiles using gin (to_tsvector('simple', coalesce(full_name, '') || ' ' || coalesce(username::text, '') || ' ' || coalesce(bio, '') || ' ' || coalesce(goals, '')));
create index collaboration_posts_recent_idx on public.collaboration_posts(status, created_at desc);
create index collaboration_posts_campus_idx on public.collaboration_posts(campus_id, created_at desc);
create index collaboration_posts_tags_idx on public.collaboration_posts using gin(tags);
create index connection_recipient_pending_idx on public.connection_requests(recipient_id, status);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger connections_set_updated_at
before update on public.connection_requests
for each row execute function public.set_updated_at();

create trigger collaborations_set_updated_at
before update on public.collaboration_posts
for each row execute function public.set_updated_at();

create or replace function public.domain_is_allowed(candidate_email text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.allowed_email_domains d
    where d.is_active
      and lower(d.domain::text) = lower(split_part(candidate_email, '@', 2))
  );
$$;

create or replace function public.is_email_domain_allowed(candidate_email text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.domain_is_allowed(candidate_email);
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, is_verified)
  values (
    new.id,
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'full_name', '')), ''),
    new.email_confirmed_at is not null and public.domain_is_allowed(new.email)
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.sync_verified_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.email_confirmed_at is not null then
    update public.profiles
    set is_verified = public.domain_is_allowed(new.email)
    where id = new.id;
  end if;
  return new;
end;
$$;

create trigger on_auth_user_verified
after update of email_confirmed_at, email on auth.users
for each row execute function public.sync_verified_profile();

create or replace function public.refresh_profile_verification()
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  verified boolean;
begin
  select u.email_confirmed_at is not null and public.domain_is_allowed(u.email)
  into verified
  from auth.users u
  where u.id = auth.uid();

  update public.profiles set is_verified = coalesce(verified, false)
  where id = auth.uid();

  return coalesce(verified, false);
end;
$$;

create or replace function public.is_verified_student(candidate_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = candidate_id and p.is_verified
  );
$$;

create or replace function public.hook_restrict_signup_by_email_domain(event jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  candidate_email text := event -> 'user' ->> 'email';
begin
  if candidate_email is not null and public.domain_is_allowed(candidate_email) then
    return '{}'::jsonb;
  end if;

  return jsonb_build_object(
    'error', jsonb_build_object(
      'http_code', 403,
      'message', 'Use an approved NST student email address to join PeerGrid.'
    )
  );
end;
$$;

revoke all on function public.domain_is_allowed(text) from public, anon, authenticated;
revoke all on function public.hook_restrict_signup_by_email_domain(jsonb) from public, anon, authenticated;
grant execute on function public.hook_restrict_signup_by_email_domain(jsonb) to supabase_auth_admin;
grant execute on function public.is_email_domain_allowed(text) to anon, authenticated;
grant execute on function public.refresh_profile_verification() to authenticated;
grant execute on function public.is_verified_student(uuid) to authenticated;

alter table public.campuses enable row level security;
alter table public.allowed_email_domains enable row level security;
alter table public.profiles enable row level security;
alter table public.skills enable row level security;
alter table public.interests enable row level security;
alter table public.profile_skills enable row level security;
alter table public.profile_interests enable row level security;
alter table public.connection_requests enable row level security;
alter table public.collaboration_posts enable row level security;

revoke all on public.campuses, public.allowed_email_domains, public.profiles,
  public.skills, public.interests, public.profile_skills,
  public.profile_interests, public.connection_requests,
  public.collaboration_posts from anon, authenticated;
grant select on public.campuses to authenticated;
grant select on public.profiles, public.skills, public.interests, public.profile_skills, public.profile_interests to authenticated;
grant insert, delete on public.profile_skills, public.profile_interests to authenticated;
grant insert on public.skills, public.interests to authenticated;
grant select, insert, delete on public.connection_requests to authenticated;
grant update (status, responded_at) on public.connection_requests to authenticated;
grant select, insert, delete on public.collaboration_posts to authenticated;
grant update (title, description, tags, campus_id, status) on public.collaboration_posts to authenticated;
grant update (username, full_name, avatar_url, campus_id, graduation_year, program, bio, goals, github_url, linkedin_url, portfolio_url) on public.profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy campuses_read on public.campuses
for select to authenticated using (is_active);

create policy profiles_read on public.profiles
for select to authenticated
using (
  id = (select auth.uid())
  or (is_verified and public.is_verified_student())
);

create policy profiles_update_own on public.profiles
for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy skills_read on public.skills
for select to authenticated using (public.is_verified_student());
create policy skills_insert on public.skills
for insert to authenticated with check (public.is_verified_student());
create policy interests_read on public.interests
for select to authenticated using (public.is_verified_student());
create policy interests_insert on public.interests
for insert to authenticated with check (public.is_verified_student());

create policy profile_skills_read on public.profile_skills
for select to authenticated
using (
  profile_id = (select auth.uid())
  or (public.is_verified_student() and public.is_verified_student(profile_id))
);
create policy profile_skills_insert_own on public.profile_skills
for insert to authenticated
with check (profile_id = (select auth.uid()) and public.is_verified_student());
create policy profile_skills_delete_own on public.profile_skills
for delete to authenticated
using (profile_id = (select auth.uid()) and public.is_verified_student());

create policy profile_interests_read on public.profile_interests
for select to authenticated
using (
  profile_id = (select auth.uid())
  or (public.is_verified_student() and public.is_verified_student(profile_id))
);
create policy profile_interests_insert_own on public.profile_interests
for insert to authenticated
with check (profile_id = (select auth.uid()) and public.is_verified_student());
create policy profile_interests_delete_own on public.profile_interests
for delete to authenticated
using (profile_id = (select auth.uid()) and public.is_verified_student());

create policy connections_read_participants on public.connection_requests
for select to authenticated
using (
  public.is_verified_student()
  and ((select auth.uid()) = requester_id or (select auth.uid()) = recipient_id)
);
create policy connections_send on public.connection_requests
for insert to authenticated
with check (
  public.is_verified_student()
  and requester_id = (select auth.uid())
  and requester_id <> recipient_id
  and public.is_verified_student(recipient_id)
);
create policy connections_respond on public.connection_requests
for update to authenticated
using (public.is_verified_student() and recipient_id = (select auth.uid()))
with check (recipient_id = (select auth.uid()));
create policy connections_remove on public.connection_requests
for delete to authenticated
using (
  public.is_verified_student()
  and ((select auth.uid()) = requester_id or (select auth.uid()) = recipient_id)
);

create policy collaborations_read on public.collaboration_posts
for select to authenticated using (public.is_verified_student());
create policy collaborations_create on public.collaboration_posts
for insert to authenticated
with check (public.is_verified_student() and author_id = (select auth.uid()));
create policy collaborations_update_own on public.collaboration_posts
for update to authenticated
using (public.is_verified_student() and author_id = (select auth.uid()))
with check (author_id = (select auth.uid()));
create policy collaborations_delete_own on public.collaboration_posts
for delete to authenticated
using (public.is_verified_student() and author_id = (select auth.uid()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 3145728, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy avatar_upload_own on storage.objects
for insert to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy avatar_update_own on storage.objects
for update to authenticated
using (bucket_id = 'avatars' and owner_id = (select auth.uid()::text))
with check (bucket_id = 'avatars' and owner_id = (select auth.uid()::text));
create policy avatar_delete_own on storage.objects
for delete to authenticated
using (bucket_id = 'avatars' and owner_id = (select auth.uid()::text));
